baseURL = "http://localhost:1313/"
languageCode = "en-us"
title = "My Magazine Site"
theme = "hugo-xmag"

# Pagination
paginate = 10

# Params for hugo-xmag
[params]
  description = "A magazine-style Hugo website."
  author = "Your Name"
  cover = "images/cover.jpg"

# Menu (optional)
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

# Enable Decap CMS editing preview
[outputs]
  home = ["HTML", "RSS", "JSON"]
