backend:
  name: github
  repo: lacritica/website   # your GitHub repo
  branch: main              # or 'master' if that’s your default branch
  base_url: https://api.github.com
  auth_type: implicit
  auth_endpoint: https://api.netlify.com/auth


media_folder: "static/uploads"    # where images will be saved in the repo
public_folder: "/uploads"         # URL path for the uploaded media

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
