backend:
  name: github
  repo: lacritica/website       # GitHub repo
  branch: main
  auth_scope: repo               # permissions needed
  base_url: https://lacritica.github.io/website/
  oauth_client_id: "Ov23libBOgj0kWggyPBa"
  oauth_client_secret: "19761c5d793f37c7c8ed3f24a4014a50510bcaf7"


media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
