backend:
  name: github
  repo: lacritica/website       # GitHub repo
  branch: main
  auth_scope: repo               # permissions needed
  base_url: https://lacritica.github.io/website/
  personal_access_token: "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"


media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
