backend:
  name: github
  repo: lacritica/website      # change if your repo has a different name
  branch: main
  auth_endpoint: https://api.netlify.com/auth

media_folder: "static/uploads"  # where uploaded images go inside the repo
public_folder: "/uploads"       # how those images are referenced in content

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "pages"
    label: "Pages"
    folder: "content"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
